In [2]:
import torch

In [3]:
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
device

device(type='cuda', index=0)

In [17]:
a = torch.ones(2, 10, 2)
b = torch.zeros_like(a)
b[..., 0] = a[..., 0]

torch.einsum("...ij,...ij->...i", a, b)

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [4]:
a = torch.randint(-10, 10, (10, 10)).to(torch.int)
torch.matmul(a, a)

tensor([[  56,  124,   -8,  -30,   16,  -87,    7,   34,   25,  113],
        [ 102,   97,  143,  -15,   37, -172,   91,  -36,  327,  113],
        [ 109,  -11,   48,  -22,  116,  -71,  -43,   29,  -11,   32],
        [  23,    1,  103,  149,   45,  -40,  136,  161,   39,  -18],
        [  67,  115,   75,   91,  265, -130,  -28,  129,   52,  -64],
        [ -57,   -7,  129,   68, -103,  126,   75,  143,   44,   46],
        [ 107,   99,   44,   13,   12, -223,  142,   15,  216,  202],
        [-109, -206,  155,  149, -223,  224,  137,   83, -109,  -43],
        [-132,  -65,  -27,   31, -167,  223,   90,  -13,   46,  -95],
        [ 119,   60,  -16,  -81,   46,  -82,   18,  124,  106,   61]],
       dtype=torch.int32)

In [5]:
a_gpu = a.to(device)
#torch.matmul(a_gpu, a_gpu)
torch.einsum("ij,jk->ik", a_gpu, a_gpu)

RuntimeError: "baddbmm_cuda" not implemented for 'Int'

In [ ]:
import bnn.functions

In [ ]:
bnn.functions.int_matmul(a_gpu, a_gpu)

tensor([[ -75,   21,    3,   14,  -43, -198,   19,  -42,  167,   96],
        [  21,  151,   -2,  -39, -161,   -5,  -52,  143, -187,  -42],
        [ -15,   -4,  -68,   39,  128,   31,  -19,  -90,  184,  -93],
        [-166,  -62, -103,  204,  -50,  -43,  -34,    2,   51,   65],
        [ 124,   59,   90,  -77,   62,  -54,   93, -236,   46, -141],
        [ 195,  103,   32, -114,   95,  -61,  173, -109,  -98, -242],
        [  40,  -17,  -78,  -54,   35,   96,  -51,  -85,  173,  -79],
        [ 178,  181,  176,  164,  107,   68,   13,   70,  152,   65],
        [  40,   55,  -20,  221,   92,  240,    6,   80,   10,  -11],
        [ -85, -101, -136,   56, -122,  -35,   34,  -89, -181,  -82]],
       device='cuda:0', dtype=torch.int32)